### ISSUE TITLE
Is there a way to set dynamically the height of #step-X container ?

### ISSUE THREAD

**Issue by kabeza** [techlab/jquery-smartwizard#101]
Hi
I'm going through steps in my wiz

The 2nd. step has a form (ajax submit)

If all goes fine in step 2, it will go to step 3 and show #divOK
If it fails, it will go to step 3 but show #divError

The problem is that they both have different heights 
Is there a way to set #step-3 container's height dynamically, after $ajax.done finished or after showing step 3 ?

Thanks

**Comment by techlab** [comment]
Fixed the issue on v6. Please see https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.1
Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/#step-1

Also added `fixHeight` public function to refresh content height from outside.
Doc: http://techlaboratory.net/jquery-smartwizard#func-fixheight

**Comment by kabeza** [comment]
Thanks Dipu!
