### ISSUE TITLE
showStep's stepIndex contains previous index

### ISSUE THREAD

**Issue by MartinP7r** [techlab/jquery-smartwizard#103]
I'm on the latest version 5.1.1

http://techlaboratory.net/jquery-smartwizard#event-showstep
```js
$("#smartwizard").on("showStep", function(e, anchorObject, stepIndex, stepDirection) {
   console.log("You are on step "+stepIndex+" now");
});
```

somehow this example is displaying the index of the previous step, not the current. E.g. when the event is trigger after moving from index  `0` to `3`, it displays `0`.

**Comment by bkeroackdsc** [comment]
Here's a really hacky way to get the current step from the browser location:

```javascript
let currentstep = parseInt(window.location.href.substring(window.location.href.indexOf("#")+1).replace("step-", ""), 10)-1;
```

**Comment by marchantm** [comment]
> Here's a really hacky way to get the current step from the browser location:
> 
> ```js
> let currentstep = parseInt(window.location.href.substring(window.location.href.indexOf("#")+1).replace("step-", ""), 10)-1;
> ```

Thanks!!!!!!!

**Comment by techlab** [comment]
Fixed the issue on v6. Please see https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.1
Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/#step-1

Thank you @MartinP7r
