### ISSUE TITLE
showStep showing Null instead of index 0 on initializing

### ISSUE THREAD

**Issue by czkoudy** [techlab/jquery-smartwizard#109]
**Describe the bug**
On first initializing of smartWizard  I get stepIndex of nothing ( just empty) of showStep event. But I would expect this to be 0 or whatever is set in selected.

When I click next it will log index  0 instead of 1 and so on.

Iam sure I am doing something wrong but cant figure this one out.

```    $(document).ready(function() {

      $('#smartwizard').smartWizard({
        theme: 'arrows',
        enableURLhash: false,
        toolbarSettings: {
          showPreviousButton: false,
          toolbarPosition: 'bottom'
        },
        anchorSettings: {
          anchorClickable: false, // Enable/Disable anchor navigation
        },
      });

      $('#smartwizard').on("showStep", function(e, anchorObject, stepIndex, stepDirection) {
        console.log(stepIndex);
      });


    });
```

**Comment by techlab** [comment]
Fixed the issue on v6. Please see https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.1
Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/#step-1
