### ISSUE TITLE
Set error problem on leavestep

### ISSUE THREAD

**Issue by reason706** [techlab/jquery-smartwizard#110]
I want to highlight an error on the step  as user click on next botton. And remove that error if the certain condition is true. I try to set error but not able to achieve.
`$('#smartwidzard').on('leaveStep', function() {
//here i  want highlight error to specific step
//here i want to remove the error from specific step

} `

**Comment by techlab** [comment]
Please try like this

```js
$("#smartwizard").on("leaveStep", function(e, anchorObject, currentStepIndex, nextStepIndex, stepDirection) {
    if (stepDirection == 'forward') {
       if (currentStepIndex == 1) {
           //here i want highlight error to specific step
       }

       if (currentStepIndex == 3) {
           //here i want to remove the error from specific step
       }
    }
});
```
