### ISSUE TITLE
markAllPreviousStepsAsDone doesn't work

### ISSUE THREAD

**Issue by Takabrycheri** [techlab/jquery-smartwizard#111]
I have enabled both enanleURLhash and markAllPreviousStepsAsDone but it doesn't mark the previous steps as done, if I put the URL of step 4 it only marks step 1 as done

**Comment by techlab** [comment]
Seems working. Please check the latest example: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/#step-1
