### ISSUE TITLE
Reload stepcontent

### ISSUE THREAD

**Issue by jacobdenis** [techlab/jquery-smartwizard#114]
Hi sir, Is their a way where we can reload the current selected step content.

i have a table inside the step3 and i have a form where the user use to add content of the table. the user was able to add data iin the database but it will not show in the table unless i will go to previous then go to step 3 again.

**Comment by ShutUpMagda** [comment]
Actually, this is not really an 'issue' (despite it can be added as one of the '_public functions_', I think), once you can do by using other resources. This can be easily achieved by setting the width height and display property of '.tab-content' with css method:

```
$('.tab-content').css({
    'width': 'automatic',
    'height': 'automatic',
    'display': 'table'
});
```
For example, if you intend to create some extra button in a supposed form:

```
$(document).on('click', '#some_btn_id', function () {
        var content = $('#some_div_content_id').html();
        var el = $("#some_target_div");
        el.append(content);
        $('.tab-content').css({
            'width':'auto',
            'height':'auto',
            'display':'table'
        });
});
```

This will automatically resize the 'tab-content' to fit the newly created elements.

**Comment by techlab** [comment]
Fixed the height issue on v6. Please see https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.1
Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/#step-1

Also added `fixHeight` public function to refresh content height from outside.
Doc: http://techlaboratory.net/jquery-smartwizard#func-fixheight
