### ISSUE TITLE
Height does not adjust for responsive content within tab

### ISSUE THREAD

**Issue by urthling** [techlab/jquery-smartwizard#116]
v5 -- Autoheight enabled - Used with a Modal

If the user changes orientation of the device or on desktop changes the size of the browser -- responsive content (eg columns that stack rather than display side-by-side) within the tab does not cause the height to readjust

Clicking to another tab and then back to the affected tab -- the height then adjusts accordingly

Is there a way to force the height to recalculate/adjust?

**Comment by urthling** [comment]
Workaround is to simply not set the `autoAdjustHeight: false `when initializing smartwizard.  Bootstrap modal will already adjust for the content.

Leaving this open because the transition height change is a nice effect -- so would be good to be able to use it

**Comment by techlab** [comment]
Fixed the issue on v6. Please see https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.1
Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/#step-1

Also added `fixHeight` public function to refresh content height from outside.
Doc: http://techlaboratory.net/jquery-smartwizard#func-fixheight
