### ISSUE TITLE
Question: Is there a way to test whether the wizard has already been initialized?

### ISSUE THREAD

**Issue by carlosalvidrez** [techlab/jquery-smartwizard#118]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by acafourek** [comment]
There is an open PR for this feature:

https://github.com/techlab/jquery-smartwizard/pull/122

**Comment by techlab** [comment]
Added initialized event. See doc: http://techlaboratory.net/jquery-smartwizard#event-initialized
