### ISSUE TITLE
Question: nav link mark as done is disabled after page is reload. 

### ISSUE THREAD

**Issue by Quadrant-RSB** [techlab/jquery-smartwizard#119]
First, would like to thank you. 

I have noticed when navigating to next (step 2) and go back to previous step (step 1) when page refresh/reload, step 2 is being disabled or not already done. Is this the current behavior of smart wizard? if so, is there any workaround to not disable previously visited step. I tried the anchor setting but I'm getting the expected result.

thanks in advance, to any expert that would help/advice me.

**Comment by techlab** [comment]
Thank you for using Smart Wizard. 
Currently the plugin not supported to persist the visited steps. But as a workaround you can `showStep` step event to store the visited step numbers on local storage or session. When the page is loaded take the highest step index and pass to the selected step.

```js
$('#smartwizard').smartWizard({
    selected: 0
});
```
