### ISSUE TITLE
how can i show toolbarExtraButtons into last wizard

### ISSUE THREAD

**Issue by vipulhanu** [techlab/jquery-smartwizard#128]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by techlab** [comment]
Make your button hidden by default and show it using the `showStep` event

```js
$("#smartwizard").on("showStep", function(e, anchorObject, stepNumber, stepDirection, stepPosition) {
    if (stepPosition === 'last') {
        $("#your-button-id").show();
    }
});
```
