### ISSUE TITLE
Cross-Site Scripting: DOM

### ISSUE THREAD

**Issue by ray-vazquez** [techlab/jquery-smartwizard#130]
When scanning my solution with Fortify the following vulnerability is flagged:

> The method init() in jquery.smartWizard.custom.js sends unvalidated data to a web browser on line 104, which can result in the browser executing malicious code.

The is a copy of the custom file with only three of the options changed from the source. Attempted to rescan with default options but the XSS issue is still flagged. Can you guys take a look at this.

#####Edit:
I'm using version 4.3.1

![gh-issuse](https://user-images.githubusercontent.com/17608112/123798121-e1dcf800-d8b4-11eb-8341-0caa34c5e1e5.PNG)

**Comment by techlab** [comment]
Hi @ray-vazquez,  this code was changed on v5, can you please check the newer version. The new code to update the URL is mentioned below, may be you can use that if you prefer to stay with the 4.x version.

```js
_setURLHash(hash) {
  if (this.options.enableURLhash && window.location.hash !== hash) {
      history.pushState(null,null,hash);
  }
}
```
