### ISSUE TITLE
Mark steps as done.

### ISSUE THREAD

**Issue by DriverOp** [techlab/jquery-smartwizard#131]
Currently there is no way to mark steps as done.
It would be nice if the "stepState" method also allowed to mark steps in that state, i.e. "done", and that this is reflected in the component interface.
Why do I ask for this feature.
Because in a wizard with many steps (+5) where the user is asked to complete a lot of data, it is necessary to implement an autosave of all the steps already completed.
So if the user leaves the wizard and then resumes it, it should tell him which steps he already completed and does not need to go back to them.

**Comment by space-bytes** [comment]
> Currently there is no way to mark steps as done. It would be nice if the "stepState" method also allowed to mark steps in that state, i.e. "done", and that this is reflected in the component interface. Why do I ask for this feature. Because in a wizard with many steps (+5) where the user is asked to complete a lot of data, it is necessary to implement an autosave of all the steps already completed. So if the user leaves the wizard and then resumes it, it should tell him which steps he already completed and does not need to go back to them.

Add this case to the switch in the stepState function:

case"done":this._setCSSClass(t,"done");break;

**Comment by techlab** [comment]
Added setState/unsetState public functions for all states. See doc: http://techlaboratory.net/jquery-smartwizard#func-setstate
