### ISSUE TITLE
smartwizard with PDOCrud 

### ISSUE THREAD

**Issue by TwinMist** [techlab/jquery-smartwizard#132]
I have the wizard working great and i am trying to add PDOCrud which is a dynamic CRUD generator application
https://pdocrud.com/demo/pages/index
it displays the table find but when i press any button the modal pop up does not show. the page flickers like it is loading. there is no errors.
I am using the following code
any ideas?
 
<div id="step2" class="tab-pane" role="tabpanel" aria-labelledby="step-2">
	<section class="content">
		<?php
		$pdocrud->formDisplayInPopup();// call this function to show forms in popup
		echo $pdocrud->dbTable("groups")->render();
	   ?>
	</section>	
</div>

**Comment by techlab** [comment]
Not sure if it is an error with Smart Wizard or the other plugin or the implementation itself. If you can provide a code pen with your implementation, may get a clue.
