### ISSUE TITLE
When trying to reset the errorSteps array to [] doesn't clear the existing steps of the error state

### ISSUE THREAD

**Issue by CoolmanPT** [techlab/jquery-smartwizard#134]
I'm using the leaveStep event to trigger some validations in the steps.
Img of the code:
![0933b9465cb62537257badf7945d35ef](https://user-images.githubusercontent.com/9550269/128887817-b3076ad6-8ae2-4de9-b68b-a1a5019e9ad9.png)

If there's an error it triggers the the setOptions:
![f461ac69080562a06b63e26fe2f97284](https://user-images.githubusercontent.com/9550269/128888272-577a0da8-628f-4e21-abcf-4e9b55cb4f10.png)

But when I fill the field and click next it doesn't remove the error state on the previous step:
![e437b172d688964a497bb9b65348c0f4](https://user-images.githubusercontent.com/9550269/128888391-3d98c42e-bc19-4d0e-9514-d7323dc00a61.png)

I'm using the smartwizard version 5.1.1

Many thanks

**Comment by Leimking** [comment]
As workaround you can set/unset them via
```
$('#smartwizard').smartWizard("stepState", [0,1], 'error-on'); //([0,1] is the step number array)
$('#smartwizard').smartWizard("stepState", [0], 'error-off');
```

**Comment by parazitenew** [comment]
> As workaround you can set/unset them via
> 
> ```
> $('#smartwizard').smartWizard("stepState", [0,1], 'error-on'); //([0,1] is the step number array)
> $('#smartwizard').smartWizard("stepState", [0], 'error-off');
> ```

Many thanks.

**Comment by techlab** [comment]
The original issue reported is fixed on v6. Thank you @CoolmanPT
