### ISSUE TITLE
fixHeight public or equivalent

### ISSUE THREAD

**Issue by ericloud** [techlab/jquery-smartwizard#135]
**Is your feature request related to a problem? Please describe.**
When an object (like a datatable) is updated and change his height dynamically, the height of the wizard isn't updated.
Which can been seen as a bug, when the wizard display only the upper part of the object (when it grow up).

**Describe the solution you'd like**
Get access to the private function [_fixHeight](https://github.com/techlab/jquery-smartwizard/blob/21681e8aea67376d2d3743b4a27b7ecdc49babaf/src/js/jquery.smartWizard.js#L744), to be able to call it when needed (after the update of a datatable or object) :
`$('#smartwizard').smartWizard("fixHeight");`

**Describe alternatives you've considered**
I try to move the object (datatable) outside of the wizard, but the interface become less intuitive for the user.
If you know an other solution, can you share it here ?

**Additional context**
Someone else ask for it last year, in an old fork 
https://github.com/mstratman/jQuery-Smart-Wizard/issues/127
And I saw similar question on Stak Overflow, like: 
https://stackoverflow.com/questions/46348911/resize-content-of-smart-wizard-js-library

Thanks for your great job and your help,
Eric.

**Comment by murilopz** [comment]
You can use this to fix height. I used it in a onChange event

$(".tab-content").height('auto');

**Comment by ericloud** [comment]
Thanks for your help.
On my side, I find a solution using `autoAdjustHeight: false` from #116.

If your solution can keep transition, it's even better.
