### ISSUE TITLE
Submit Form Handler

### ISSUE THREAD

**Issue by ateequrrahman97** [techlab/jquery-smartwizard#136]
**Is your feature request related to a problem? Please describe.**
If the smart wizard has a form submit handler/ form finish handler that can describe the form completion. like leaveStep event then we can better handle the form submission manually and add some functionality on form submit like validator / ajax requests etc.

**Describe the solution you'd like**
Like the leaveStep event in the wizard, we can add event/function on form completion/finish then the user will be able to add some functionality on form submit like validator / ajax requests, etc.

**Describe alternatives you've considered**

**Additional context**
@techlab

**Comment by techlab** [comment]
Hi @ateequrrahman97,  https://github.com/techlab/jquery-smartwizard/issues/20#issuecomment-286723131 here is the code spinet that does the functionality you, it has an example on how to do ajax calls on each step progress, hope it helps.
