### ISSUE TITLE
unable to hide previous and next button...

### ISSUE THREAD

**Issue by sandy15d** [techlab/jquery-smartwizard#139]
$('#smartwizard').smartWizard({
                selected: 0,
                theme: 'default',
                autoAdjustHeight:true,
                transition: {
                    animation: 'slide-horizontal', // Effect on navigation, none/fade/slide-horizontal/slide-vertical/slide-swing
                },
                toolbarSettings: {
                    toolbarPosition: 'none', 
                }
            });

**Comment by techlab** [comment]
Please try the options `showNextButton` and `showPreviousButton`

```js
$('#smartwizard').smartWizard({
    toolbar: {
      showNextButton: false, // show/hide a Next button
      showPreviousButton: false // show/hide a Previous button
    }
});
```
