### ISSUE TITLE
Navigation tht is not allowed

### ISSUE THREAD

**Issue by hn1** [techlab/jquery-smartwizard#140]
If you do not allow navigation to a step, all you have to do is for the user to type in the address bar and refresh and VOILLA! - they get to the next step without having to complete the previous step.
But in general, a very good work - well done.

**Comment by techlab** [comment]
Fixed the issue on v6. Please see https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.1
Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/#step-1
Thank you @hn1

**Comment by hn1** [comment]
Excellent. Thank you for a great tool.
