### ISSUE TITLE
Uncaught TypeError: $(...).smartWizard is not a function

### ISSUE THREAD

**Issue by gtezini** [techlab/jquery-smartwizard#141]
Hi,
I really don't know whats happening, but the component does not work inside any ASP.NET MVC CORE (5.0) Projects.

When i try to **initialize** the component i receive the message:
**Uncaught TypeError: $(...).smartWizard is not a function**

Outside the project, as a simple HTML page for example, the component works fine.

Please, do you have any idea whats going on?

Thank you!

**Comment by techlab** [comment]
Hi @gtezini Probably because of some implementation issue. Please post this question on StackOverflow for better response under the smart-wizard tag.  https://stackoverflow.com/questions/tagged/smart-wizard
Closing the issue because it is not directly related with the plugin.
