### ISSUE TITLE
rtl page arrow must be to left on  theme: 'arrows',

### ISSUE THREAD

**Issue by Arafat-Thabet** [techlab/jquery-smartwizard#144]
theme: 'arrows',
rtl direction arrow must be to left
like that <=,<=
but know show like =>,=>

**Comment by techlab** [comment]
Please check the v6 with RTL support. 
Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/rtl#step-1
Docs: http://techlaboratory.net/jquery-smartwizard#rtl-support
