### ISSUE TITLE
enableURLhash option not working on v6.x

### ISSUE THREAD

**Issue by AComasSamcla** [techlab/jquery-smartwizard#147]
Seems that enableURLhash option does not work anymore.

I set it to true, but mantains the same behaviour as it was true as default (hash now appears on URL and if you manually change it it navigates to that step). I don't want to display step hash on URL nor let user introduce it on URL, as it was on previous major version.

Just upgraded from v5.x and appeared this issue, so probably it is a new bug introduced on v6.x

**Comment by techlab** [comment]
Please use with the case `enableUrlHash` than enableURLhash

**Comment by AComasSamcla** [comment]
Sorry, my bad, you are correct. I didn't notice de case.

Thanks
