### ISSUE TITLE
 Uncaught TypeError: $(...).smartWizard is not a function

### ISSUE THREAD

**Issue by amir3164** [techlab/jquery-smartwizard#151]
i'm use smartWizard see this error $(...).smartWizard is not a function
when download sample
![Untitled](https://user-images.githubusercontent.com/10501720/183287500-7e321492-fc3a-45c3-9587-140d27920c07.png)

**Comment by techlab** [comment]
Couldn't reproduce the issue, please make sure the path for the included plugin is correct.
