### ISSUE TITLE
How to remove next step when on last page

### ISSUE THREAD

**Issue by vincejairam-VisionMedia** [techlab/jquery-smartwizard#170]
On the last step, the next button is disable. How can I remove it as users found it confusing when on the last step.

**Comment by nikesh9220** [comment]
You can implement 'leavestep' event and check if the next step is your last step then write `  $('.sw-btn-next').hide();` code to hide the Next button.

**Comment by vincejairam-VisionMedia** [comment]
thanks @nikesh9220 that did it 👍
