### ISSUE TITLE
Make the step anchor center

### ISSUE THREAD

**Issue by duongtdvn** [techlab/jquery-smartwizard#27]
Hi,

Is it possible to make the step anchor to be center just like the bootstrap `nav-justified` class.

Thank you!

**Comment by serifreedom** [comment]
I wonder if it possible to completely hide anchor if need too?

**Comment by techlab** [comment]
Thank you @duongtdvn for the recommendation. This option is added on the new version jQuery SmartWizard v5 #87 

It can be switched with an option parameter which is enabled by default.

```javascript
$('#smartwizard').smartWizard({
  justified: true, // Nav menu justification. true/false
});
````

**Comment by techlab** [comment]
@serifreedom Hide anchor option is available from v4 itself. 

```javascript
// Hide step
$('#smartwizard').smartWizard("stepState", [2], "hide");
````
