### ISSUE TITLE
How to go to next dynamically visible step right after making them dynamically visible? 

### ISSUE THREAD

**Issue by xihad76** [techlab/jquery-smartwizard#35]
I have total 8 steps in my form. Among them number 0 and 7 are active on load and the rest are hidden. I am conditionally making them visible on leaveStep on step 0. It works fine except it goes directly to step 7 instead of going to step 1. how can I fix this?

**Comment by andresrex** [comment]
Yeah, how to go to step?

**Comment by asoltani927** [comment]
Hi

I inserted this code to jquery.smartwizard.js:
after  _showNext function

` _goToStep: function (v) {
            var si = v;

            if (this.steps.length <= si) {
                if (!this.options.cycleSteps) {
                    return false;
                }
                si = 0;
            }

            // Find the next not disabled step
            for (var i = 0; i < si; i++) {
                this._showStep(i);
            }

            return true;
        },`
after theme function:

        `goTo: function (v) {
            this._goToStep(v);
        },`

Then try the following code



`
var step = 5;
$("#smartwizard").smartWizard("goTo",step);
`

**Comment by techlab** [comment]
Please try the new jQuery Smart Wizard v5 #87 this issue should have fixed.
