### ISSUE TITLE
Toolbar not on right position due to navbar class attribute on material Admin Template

### ISSUE THREAD

**Issue by sushiljic** [techlab/jquery-smartwizard#37]
When using smart wizard on material Admin Template (https://github.com/gurayyarar/AdminBSBMaterialDesign) ,I am getting such issue with toolbar due to navbar class property being attached to nav tag.
Below is the screenshot
![image](https://user-images.githubusercontent.com/5524563/30304059-46371822-978b-11e7-984f-6de3963ec5c2.png)

**Comment by techlab** [comment]
Please try the new jQuery Smart Wizard v5 #87 this issue should have fixed.
