### ISSUE TITLE
Acept Promise on return of "leaveStep" event.

### ISSUE THREAD

**Issue by albertoVieiraNeto** [techlab/jquery-smartwizard#47]
hi.

I think the plugin is awsome, but there still some points of inprovement. for example i would like to be able to have the ability to return a jquery promise or a native promise on the leaveStep event:

Can i make the necessary modifications and make a pull-request?

currently i'm using something similar to this: https://github.com/techlab/SmartWizard/issues/20

Example:
```javascript
$("#smartwizard").on("leaveStep", function (e, anchorObject, stepNumber, stepDirection) {
	
	//we could have a jquery ajax or something else here
	return new Promise(function(resolve, reject){ resolve(true)})

})

```

**Comment by techlab** [comment]
Hi @albertoVieiraNeto 
It is a great idea you come up with, please feel free to make the pull request to `dev` branch. Thank you so much.

**Comment by nusoft** [comment]
@albertoVieiraNeto Did you manage to get this working with a Promise?

**Comment by michaelpev** [comment]
Hi guys, I am *REALLY* keen to see this implemented; I am attempting to get SmartWizard working with AJAX, & none of the suggested workarounds are able to do what I need. I am willing to discuss paying you for your time to get this sorted - please feel free to reach out to me

**Comment by michaelpev** [comment]
I am using SmartWizard in an ASP .Net core MVC application, & want to use View Components (like partial views) and AJAX for each step in my wizard. In order to do server side validation, AJAX is required to return validation events (e.g. if form doesnt validate, AJAX function returns validation messages, & does not allow you to move to next step; if successful, move to next step

**Comment by techlab** [comment]
Thank you again @albertoVieiraNeto for the suggestion, this is implemented in the new version of jQuery Smart Wizard v5 #87 

The ajax content can be loaded via an event `stepContent` with the help of Promise. 

Read more about the implementation http://techlaboratory.net/jquery-smartwizard#ajax_contents
Ajax example page http://techlaboratory.net/projects/demo/jquery-smart-wizard/v5/ajax

cc @nusoft @michaelpev

**Comment by chobo2** [comment]
> Thank you again @albertoVieiraNeto for the suggestion, this is implemented in the new version of jQuery Smart Wizard v5 #87
> 
> The ajax content can be loaded via an event `stepContent` with the help of Promise.
> 
> Read more about the implementation http://techlaboratory.net/jquery-smartwizard#ajax_contents
> Ajax example page http://techlaboratory.net/projects/demo/jquery-smart-wizard/v5/ajax
> 
> cc @nusoft @michaelpev

How about "LeaveStep" does that support promises? I have the same problem as @michaelpev as I need to do server side validation and bring back the results. If validation fails I don't want to leave that step. If I do this validation in "StepContent" the wizard has already visually moved to the next step which I don't want.

**Comment by techlab** [comment]
@chobo2 I get that point with the "LeaveStep" to accept promises, I will look into the possibility of include it on the next versions. 
In the mean time, there is already a workaround to handle the case, please refer https://github.com/techlab/jquery-smartwizard/issues/20

**Comment by chobo2** [comment]
> @chobo2 I get that point with the "LeaveStep" to accept promises, I will look into the possibility of include it on the next versions.
> In the mean time, there is already a workaround to handle the case, please refer #20

Yep, that is what I implemented  but think a promise way would be cleaner.
