### ISSUE TITLE
Translate validation messages

### ISSUE THREAD

**Issue by danilosantosdev** [techlab/jquery-smartwizard#48]
Hi all!

I put validation form um many steps of smartwizard, but the messages are shown in English. How can i translate that messages? In my case to Portuguese.

Thanks!

![opera snapshot_2018-04-09_112538_danilo marte qlfo](https://user-images.githubusercontent.com/2335679/38503553-c0d00754-3be8-11e8-8a71-beff57f690aa.png)

**Comment by AbuTabikh** [comment]
you have two options

1. change your browser language from English to Portuguese
2. override error message by adding data-required-error="text here" into your field
e.g. `<input type="text" class="form-control" name="name"  placeholder="Insert name" required data-required-error="Fill this, Please!!">
`
