### ISSUE TITLE
SmartWizard+DataTables

### ISSUE THREAD

**Issue by jwmwalrus** [techlab/jquery-smartwizard#49]
Hi.

I'm using v4.2.2 (since I'm still on Bootstrap 3), combined with DataTables 1.10.16.  When I put a datatable in one of the steps of the wizard, portions of the datatable (and any elements below) become readonly ---i.e., they cannot be clicked at all.

Example:
* I have a wizard with two steps;
* I put a datatable with two rows in the second step of the wizard;
* I also put a button below the datatable
* **The button becomes readonly and cannot be clicked**.

Another example:
* I have a wizard with two steps;
* I put a datatable, with 5 rows, with selection checkboxes in the first column of each row, also in the second step of the wizard;
* **Only the checkboxes in the first two rows can be clicked**.

That (mis)behavior occurs only after the first step of the wizard.  Datatables in the first step of the wizard work properly.

Is there a known conflict between SmartWizard an other jQuery plugins?  Any ideas on workarounds?

I'm using jQuery v3.2.1.

**Comment by MrFFC0CB** [comment]
+1. Have same problem.

**Comment by techlab** [comment]
Please try the new jQuery Smart Wizard v5 #87 
The new version comes with standalone CSS, which is also compatible with Bootstrap.
