### ISSUE TITLE
Responsive Issues with Latest Bootstrap

### ISSUE THREAD

**Issue by marcodeluca** [techlab/jquery-smartwizard#52]
Using <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet"/> or above, steps (nav-links) are no longer responsive.

This is what I did to fix it, not quite a universal solution but you get the idea. It makes the nav list equal width, and then forces it to wrap at smaller screen widths.

```
.sw-theme-default > ul.step-anchor > li {
    position: relative;
    margin-right: 2px;
    flex-grow: 1;
    flex-basis: 0;
}
@media(max-width:767px) {
    .sw-theme-default > ul.step-anchor {
        flex-wrap:wrap;
    }
    .sw-theme-default > ul.step-anchor > li {
        flex: 0 0 49%;
    }
    .sw-theme-default > ul.step-anchor small {
        display: none
    }
}
```

**Comment by techlab** [comment]
Please use the new jQuery Smart Wizard v5 #87 
The CSS is now stand alone with Bootstrap support and also responsive.
