### ISSUE TITLE
Step description showing up while not formatted yet

### ISSUE THREAD

**Issue by ligoo** [techlab/jquery-smartwizard#54]
When you load the page, the step section will show up without formatting and then after a few milliseconds, it will get the correct styling.

This can be avoided by calling smartWizard this way: `$('#smartwizard').smartWizard().children('ul').removeClass('d-none');` and by adding a `<ul class = "d-none">` to the step section (or equlivalent if you work with bootstrap 3)

**Comment by bijeesraj007** [comment]
Thanks @ligoo ! the solution worked for me.

**Comment by techlab** [comment]
Thanks for the solution @ligoo
