### ISSUE TITLE
Bootstrap 3

### ISSUE THREAD

**Issue by 19peaches** [techlab/jquery-smartwizard#55]
In the latest version the javascript uses quite a bit of bs4 selectors and classes.

I'm currently needing to use this in a BS3 project that isn't slotted for upgrade to BS4 for quite some time.  How far back do I need to go version wise to get to a version that uses only BS3 selectors in the javascript?

Thanks a bunch, great package!

**Comment by doukai** [comment]
use version 4.2.x

**Comment by techlab** [comment]
Please use the new version jQuery Smart Wizard v5 #87 It has standalone CSS with Bootstrap compatibility.
