### ISSUE TITLE
Change dynamically the data parameter of ajaxSettings

### ISSUE THREAD

**Issue by luiseduardo** [techlab/jquery-smartwizard#56]
I change "_loadStepContent" method to check if ajaxSettings is string and then eval this, works, but,  i dont no if is the best solution.

**Comment by techlab** [comment]
@luiseduardo In the new version of jQuery Smart Wizard v5 #87, the ajax content can be loaded via an event `stepContent` with the help of Promise. So you will have the full control over the ajax calls and you only have to pass the content when available.  

Read more about the implementation http://techlaboratory.net/jquery-smartwizard#ajax_contents
Ajax example page http://techlaboratory.net/projects/demo/jquery-smart-wizard/v5/ajax
