### ISSUE TITLE
Demo next button bug

### ISSUE THREAD

**Issue by adnathanail** [techlab/jquery-smartwizard#57]
Hi, found a bug on the [demo](http://techlaboratory.net/smartwizard/demo):
If you go to the last step and reset the wizard with either the internal or external button, the external next button looks disabled. It does however still function and as soon as you click it to go to step 2 it regains its proper style

**Comment by techlab** [comment]
Thank you for reporting that issue @adnathanail 
Issue is fixed on the latest demo
http://techlaboratory.net/jquery-smartwizard#demo
