### ISSUE TITLE
Form field data is lost on page refresh in CHROME

### ISSUE THREAD

**Issue by marcodeluca** [techlab/jquery-smartwizard#59]
Using the stock example in Firefox, you can enter field data and refresh the page and your data is still there: http://techlaboratory.net/demos/SmartWizard43/examples/smartwizard-input.html#step-1

Do the same in chrome and the data is lost. Is this a known issue? Can it be resolved?

**Comment by techlab** [comment]
@marcodeluca It seems like the browser behaviour, that is not in the scope of the plugin. Thanks for your query.
