### ISSUE TITLE
z-index component inside

### ISSUE THREAD

**Issue by studio4s** [techlab/jquery-smartwizard#66]
I have a datepicker component and the widget window is cut from the edge of the container
![trovacigusto localhost_catering_2_admin_offers_26971](https://user-images.githubusercontent.com/25401693/51314072-59a16a00-1a4f-11e9-974d-e9d404ef95bf.png)

**Comment by techlab** [comment]
Please try the new jQuery Smart Wizard v5 #87. The issue should have fixed.
