### ISSUE TITLE
Incorrect version numbers in releases

### ISSUE THREAD

**Issue by daviddavid** [techlab/jquery-smartwizard#68]
The bundled releases contain the wrong version numbers. [v4.3.1](https://github.com/techlab/SmartWizard/tree/v4.3.1) still contains the v4.2.2 version number. Going back, this has been the case for all releases I bothered to check. This throws off bower installs which relies on the version numbers to be consistent.

**Comment by techlab** [comment]
Thanks for reporting that, Bower is not supporting now. Please use [npm](https://www.npmjs.com/package/smartwizard) or [Yarn](https://yarn.pm/smartwizard).
