### ISSUE TITLE
rtl suport

### ISSUE THREAD

**Issue by amir3164** [techlab/jquery-smartwizard#72]
i want   step wizard to right to left

**Comment by zandiarash** [comment]
> i want step wizard to right to left

Yes I want RTL too,
Dear developers is there any solution ?

**Comment by MojtabaFaal** [comment]
**CSS normal to RTL**
Convert "smart_wizard_all.css" with ["https://rtlcss.com/playground/index.html"](https://rtlcss.com/playground/index.html) website

**Comment by techlab** [comment]
jQuery Smart Wizard v6 now has built in RTL support.
Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/rtl#step-1
Docs: http://techlaboratory.net/jquery-smartwizard#rtl-support
