### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by fpolito** [techlab/jquery-smartwizard#76]
why I have to install twbs bootstrap 4.0.0-alpha.6 ?
I can install yii2-bootstrap4, adding 
"yiisoft/yii2-bootstrap4": "@dev"
in the "require-dev"section of composer.json file

You should remove
        "twbs/bootstrap": ">=4.0.0"
from the "require" section of your composer.json file.
The same for "components/jquery": ">=3.3.1"

Now to install the last release of techlab/SmartWizard , and have "minimum-stability": "stable" in the yii2 composer.json file, I have to insert
"techlab/smartwizard": "@dev"
in the "require-dev"section of the composer.json file.

**Comment by techlab** [comment]
The issue is fixed. Thanks for reporting.
