### ISSUE TITLE
API Success Forward next step issue

### ISSUE THREAD

**Issue by RajuTicvic** [techlab/jquery-smartwizard#79]
Hi @techlab 
I got the api response success but im facing the issues is
1. Step not forward next step
2. The api is running infinity.
I think the issue from `$('#smartwizard').smartWizard("next");`
<img width="1280" alt="Screenshot 2019-11-13 at 4 31 58 PM" src="https://user-images.githubusercontent.com/47621807/68758442-d8494280-0633-11ea-8179-9b75ca2f1c32.png">
<img width="2046" alt="Screenshot 2019-11-13 at 4 37 29 PM" src="https://user-images.githubusercontent.com/47621807/68758518-f44ce400-0633-11ea-909b-31e795821be2.png">

**Comment by techlab** [comment]
Please check the answer here, https://github.com/techlab/jquery-smartwizard/issues/20#issuecomment-286723131

The issue is that, since you are calling the `next` on the `leaveStep` event fire again like in a loop. You will have to add a flag to avoid that, something like this.

```javascript
var ajaxInvoke = false;
$wizard.on('leaveStep', function(e, anchorObject, stepNumber, stepDirection) {
  if (stepDirection === 'forward' && stepNumber === 2 && ajaxInvoke ==false) {
   ajaxInvoke = true;
    $.ajax({
      method: 'POST',
      url: url,
      data: data
    }).then(function (response) {
      // indicate the ajax has been done, release the next step
      $wizard.smartWizard("next");
    }, function (){
      // hang on this step if the error occur
    });
   return false;
  }
});
```
