### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by hellboy81** [techlab/jquery-smartwizard#80]
Any alternatives?

**Comment by ruuttt** [comment]
I really like this project. Maybe the project can be brought back to life, if all readers of this message make a small paypal donation (see last section of README.md for payment link) or send the project owner a message via [https://www.linkedin.com/in/dipuraj/]

**Comment by techlab** [comment]
@hellboy81 not dead yet, new version v5 #87 is released http://techlaboratory.net/jquery-smartwizard

Few alternatives I see are:
http://www.jquery-steps.com/Examples
http://kflorence.github.io/jquery-wizard/examples/
https://www.sitepoint.com/jquery-form-wizard-plugins/  

Thank you @ruuttt for your likes and initiative, hope you like the new version v5.
