### ISSUE TITLE
Next step doesn't work if you use go to step feature

### ISSUE THREAD

**Issue by arahmancsd** [techlab/jquery-smartwizard#85]
**Describe the bug**
I found a bug while using the goToStep which the next step doesn't fire unless you go to previous step and then next step.

**To Reproduce**
I have four steps. 
1. Go to the last step or any step other than 1 & 2. 
2. From the current step (e.g step -> 3), use gotoStep option to go to previous step (e.g step -> 2)
3. The next button doesn't work and it doesn't move forward unless you step back and then next.

**Expected behavior**
When you use gotoStep to move to previous step. e.g from step -> 4 to step -> 2 The next button should work, but it doesn't work. 
In my case the external button which moves to the next step doesn't work.

**Desktop (please complete the following information):**
 - Linux
 - Firefox
 - Version 75.0 (64bit)

**Comment by techlab** [comment]
Thank you @arahmancsd for reporting the issue. The problem has been fixed on the new version  v5 of jQuery Smart Wizard. #87 
Please see the demo and details here http://techlaboratory.net/jquery-smartwizard
