### ISSUE TITLE
Smartwizard V5.0.0 - Responsive design don't work with transition effects

### ISSUE THREAD

**Issue by argawow** [techlab/jquery-smartwizard#88]
With transition-animation: 'slide-h' the responsiveness doesn't work properly. The content is not centered in the viewing window on / after risize. After switching to another tab, the view is correct again.

Here are the settings I am using:

`   $('#smartwizard').smartWizard({
        selected: 0,  // Initial selected step, 0 = first step
        theme: 'default',
        justified: false,
        keyNavigation: true, // Enable/Disable keyboard navigation(left and right keys are used if enabled)
        autoAdjustHeight: true, // Automatically adjust content height
        cycleSteps: false, // Allows to cycle the navigation of steps
        backButtonSupport: true, // Enable the back button support
        useURLhash: true, // Enable selection of the step based on url hash
        transition: {
            animation: 'slide-h', // Effect on navigation, none/fade/slide-horizontal/slide-vertical/slide-swing
            speed: '400', // Transion animation speed
            easing: '' // Transition animation easing. Not supported without a jQuery easing plugin
        },
        //contentCache: true,
        //hiddenSteps: [2, 3],
        lang: {  // Language variables
            next: nextButton,
            previous: backButton
        },
        toolbarSettings: {
            toolbarPosition: 'bottom', // none, top, bottom, both
            toolbarButtonPosition: 'right', // left, right
            showNextButton: true, // show/hide a Next button
            showPreviousButton: true, // show/hide a Previous button
            toolbarExtraButtons: [
                btnFinish, btnCancel
            ]
        },
    });`

**Comment by kabeza** [comment]
Hi
I'm having same issue
When I enable transitions, responsive does not work

I've removed this from settings

```
transition: {
    animation: 'slide-horizontal', // Effect on navigation, none/fade/slide-horizontal/slide-vertical/slide-swing
},
```

And now all is working fine

Hope it can be fixed soon

Thanks

**Comment by Drigtime** [comment]
Had the same issue, instead of removing the animation like @kabeza did, I switched to a **fade** animation and now it seems to work just fine

**Comment by techlab** [comment]
Fixed the issue on v6. Please see https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.1
Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/#step-1

Also added `fixHeight` public function to refresh content height from outside.
Doc: http://techlaboratory.net/jquery-smartwizard#func-fixheight

**Comment by kabeza** [comment]
thanks Dipu! Awesome job
