### ISSUE TITLE
How to determine the source of triggering leaveStep event?

### ISSUE THREAD

**Issue by musiko** [techlab/jquery-smartwizard#92]
I would like to determine the source of triggering `leaveStep` event and perform different actions in the event handler accordingly, i.e.
1. Triggered by clicking the 'Next' button
2. Triggered by calling `$('#smartWizard').smartWizard('next')` or `$('#smartWizard').smartWizard('goToStep', 2)`

Could you provide an advice? Thank you in advance.

**Comment by techlab** [comment]
This is not handled internally right now. $('#smartWizard').smartWizard('next') and $('#smartWizard').smartWizard('goToStep', 2) should be invoked externally, so you could add a flag there to recognise the source and anything other than is from the next button inside.
