### ISSUE TITLE
autoAdjustHeight does not work

### ISSUE THREAD

**Issue by ruuttt** [techlab/jquery-smartwizard#93]
When divs are added to a tab via JavaScript, the tab height will change and some content falls off the page. I created the following work around. Would be great if you could fix it, so I don't need the workaround anymore. 

```javascript
var MyOuterHeight=0;
$(document).ready(function () {
	$('#smartwizard').smartWizard();
	setInterval(function(){
		var stepIndex = $('#smartwizard').smartWizard("getStepIndex");
		var tab = $('#smartwizard>.tab-content>.tab-pane:nth-child('+stepIndex+')');
		var myHeight = tab.outerHeight();
		if (myHeight!=MyOuterHeight){
			MyOuterHeight=myHeight;
			$('#smartwizard>.tab-content').animate({height:myHeight},400);
		}	
	}, 100);
});
```

**Comment by techlab** [comment]
Thank you @ruuttt for the code. I will look into it and try to add fix on the upcoming release. Appreciate all your effort.

**Comment by cobia** [comment]
+1:  I too am looking forward to a resolution to this bug. This issue wasn't in version 4.
