### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by tjburke79** [techlab/jquery-smartwizard#95]
this is a great script, it says that it has support for validation, but i am having a hard to adding jquery validation.  can you show a simple example of getting this to work?

**Comment by pupattan** [comment]
Please help

**Comment by eggman89** [comment]
```
   
    $("#smartwizard").on("leaveStep",  function(e, anchorObject, currentStepIndex, nextStepIndex, stepDirection) {

        
        //for "Next"
        if (currentStepIndex === 0 && stepDirection === 'forward'){
            return doValidation()
        }
        
        
        {#For Previous#}
        if (currentStepIndex === 1 && stepDirection === 'backwards'){
            return doValidation()
        }

    });
    ```

**Comment by techlab** [comment]
Please see the jQuery Smart Wizard Form Validation Demo http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/validation#step-1

See code example here: https://github.com/techlab/jquery-smartwizard/blob/master/examples/validation.html
