### ISSUE TITLE
Keyboard setttings don't work at all

### ISSUE THREAD

**Issue by simon-spier0** [techlab/jquery-smartwizard#96]
Key left and key right can't be changed nor even disabled.
```
keyboardSettings: {
	keyNavigation: true,
	keyLeft: [74], // J key code
	keyRight: [75] // K key code
}
```
```
keyboardSettings: {
	keyNavigation: false,
}
```

Could you please fix it?

**Comment by techlab** [comment]
@simon-spier0 It works on my tests, see the example pen https://codepen.io/techlab/pen/JjGZvaz
Or is it on any specific browser or OS?

**Comment by simon-spier0** [comment]
> @simon-spier0 It works on my tests, see the example pen https://codepen.io/techlab/pen/JjGZvaz
> Or is it on any specific browser or OS?

Oh, thanks, it works now. It didn't work in version 4.4.1. :)
