### ISSUE TITLE
5.1.1 - stepDirection on leaveStep return the stepIndex

### ISSUE THREAD

**Issue by argawow** [techlab/jquery-smartwizard#97]
I am on the latest release 5.1.1 updated from 5.0.0

I am using the "leaveStep-Event" to check the form is valid. For this I use the "forward" attribute. 

On this release I get the StepIndex instead of the stepDirection on the direction Attibute.

On 5.0.0 everthing is working like expected.

I hope you can fix this soon :)

**Comment by techlab** [comment]
@argawow `stepDirection` is the 5th parameter now. 4rd parameter is the index of the next step to be shown. Please update your event code also.

```js
$("#smartwizard").on("leaveStep", function(e, anchorObject, currentStepIndex, nextStepIndex, stepDirection) {
   return confirm("Do you want to leave the step " + currentStepIndex + "?");
});
```

Please see the details here http://techlaboratory.net/jquery-smartwizard#event-leavestep
