### ISSUE TITLE
Content not showing when used inside a Bootrap 4 modal

### ISSUE THREAD

**Issue by krismanning** [techlab/jquery-smartwizard#98]
**Describe the bug**
When running inside a BS modal the content of step 1 (or any other step) isn't showing when the modal and smart wizard loads. If you tap the Previous/Next buttons then the content shows.

Looking at the browser (Chrome) inspector I can see that the tab-content height is being set to 0px by smartwizard and when you hit the previous/next buttons then the height is appropriately set and the content appears

To fix the issue I had to use **autoAdjustHeight: false,** and everything works fine but that seems like a workaround so wanted you to know.

Latest versions of smartwizard, bootstrap and jquery being used.

Thanks for a great component.

Kris

**Comment by davidboybob** [comment]
Thanks. I had the same bug.

**Comment by sorinsfirlogea** [comment]
Still not fixed, one year and a half later. :-(

**Comment by iltekin** [comment]
Same in April 2022.

**Comment by techlab** [comment]
Fixed the issue on v6. Please see https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.1
Please see Bootstrap Modal Demo: http://techlaboratory.net/projects/demo/jquery-smart-wizard/v6/bootstrap-modal#step-1
